name: Update Proxy Keys

on:
  schedule:
    - cron: '0 */12 * * *' # Запуск каждые 12 часов
  workflow_dispatch:      # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Script
        run: python main.py

      - name: Commit and Push results
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add whitelist_keys.txt blacklist_keys.txt
          git commit -m "Auto-update keys: $(date)" || echo "No changes to commit"
          git push
